Add files via upload

diff --git a/step.yml b/step.yml
--- a/step.yml
+++ b/step.yml
@@ -1,48 +1,70 @@
 title: Script
 summary: |-
-  The power is in your hands. Use it wisely!
+  Run any custom script you want. The power is in your hands. Use it wisely!
 description: |-
-  Specify the script content and (optionally) the script runner
-  binary and this step will execute it.
 
-  The *runner* can even be a command, if it's available in the PATH
-  and can execute the script it will work.
+  Run any custom script you want as part of your Bitrise build. All you need to do is specifying the script runner  
+  (the default is bash), add the script, and run a build. 
+  
+  You can also read the script from a file.
 
-  For example to run a [Go](https://golang.org/) Hello World "script"
-  you can define the content:
+  ### Configuring the Step
 
-      package main
-      import "fmt"
-      func main() {
-          fmt.Println("hello world")
-      }
+  1. Set the **Execute with/runner binary** input.
 
-  Set the *Execute with* parameter to `go run` and specify
-  a *script file path* because `go run` can only accept (at the moment)
-  files with a .go extension (just specify `step.go` as the script path).
+     Either define the path of the executor, or simply just add its name if you know it is available in the PATH, such as `ruby` or `python`. It can even be a command, such as `go run`.  
 
-  If the `go` binary can be found in the PATH your Hello World
-  script will run without any problem.
+  1. Write your script in the **Script content** input or specify a script file.
+
+     If you have a script in your repository, you can simply run it from the file, either by calling it in the **Script content** input  
+     or, optionally, by specifying the path to it in the **Script file path** input. 
+     
+     Be aware that relative paths are relative to the value set in the **Working directory** input - by default, it is your app's source directory.
+
+  ### Troubleshooting
+
+  If the script fails, check the executor first - obviously, a Python script will not work with a bash runner.
+
+  Note that in certain cases, the filename or the filepath actually matters. For example, the `go run` command only accepts `.go` files.
+
+  ### Useful links
+
+  * [System reports to check out the pre-installed executors](https://github.com/bitrise-io/bitrise.io/tree/master/system_reports)
+  * [Exporting to Test Reports from custom Script Steps](https://devcenter.bitrise.io/testing/exporting-to-test-reports-from-custom-script-steps/)
+
+  ### Related Steps
+
+  * [Script Runner](https://www.bitrise.io/integrations/steps/script-runner)
+  * [Remote Bash Script Runner](https://www.bitrise.io/integrations/steps/remote-script-runner)
 website: https://github.com/bitrise-io/steps-script
 source_code_url: https://github.com/bitrise-io/steps-script
 support_url: https://github.com/bitrise-io/steps-script/issues
 host_os_tags:
-  - osx-10.10
+  - osx
+  - ubuntu
 project_type_tags: []
 type_tags:
-  - script
+  - utility
 is_requires_admin_user: false
 is_always_run: false
 is_skippable: false
 inputs:
   - content: |-
-      #!/bin/bash
+      #!/usr/bin/env bash
       # fail if any commands fails
       set -e
+      # make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
+      set -o pipefail
       # debug log
       set -x
 
-      echo "Hello Bitrise!"
+      # write your script here
+      echo "Hello World!"
+
+      # or run a script from your repository, like:
+      # bash ./path/to/script.sh
+      # not just bash, e.g.:
+      # ruby ./path/to/script.rb
     opts:
       title: "Script content"
       description: |
@@ -54,6 +76,7 @@ inputs:
       is_required: true
   - runner_bin: "/bin/bash"
     opts:
+      category: Config
       title: "Execute with / runner binary"
       description: |
         The executor to be used for running the script.
@@ -64,29 +87,20 @@ inputs:
 
         You can even specify an execution command
         like `go run` instead of just a binary.
-      is_expand: false
       is_required: true
-  - is_debug: "no"
+  - working_dir: "$BITRISE_SOURCE_DIR"
     opts:
-      title: "Debug?"
-      description: |
-        If debug=yes the step will print debug infos about
-        the working dir, tmp file path, exit code, etc.
-      value_options:
-        - "no"
-        - "yes"
-      is_expand: false
-      is_required: false
-  - working_dir:
-    opts:
+      category: Config
       title: "Working directory"
       description: |
         This directory will be set as the current working
         directory for the script.
-      is_expand: true
-      is_required: false
-  - script_file_path:
+
+        Any relative path in the Script (content) will be
+        relative to this directory.
+  - script_file_path: ""
     opts:
+      category: Config
       title: "Script file path"
       description: |
         Save the specified script content to this path
@@ -100,6 +114,14 @@ inputs:
 
         If you specify a relative path then it will be
         relative to the *working directory* (which you
-        can optinally specify as well).
-      is_expand: true
-      is_required: false
+        can optionally specify as well).
+  - is_debug: "no"
+    opts:
+      category: Debug
+      title: "Debug print?"
+      description: |
+        If debug=yes the step will print debug infos about
+        the working dir, tmp file path, exit code, etc.
+      value_options:
+        - "no"
+        - "yes"
